[data]
train_file = "/cs336/assignment1/data/TinyStoriesV2-GPT4-train.tokens.npy"
validation_file = "/cs336/assignment1/data/TinyStoriesV2-GPT4-valid.tokens.npy"

[model]
vocab_size = 10000
context_length = 256
d_model = 512
d_ff = 1344
rope_theta = 10000.0
num_layers = 4
num_heads = 16
device = "cuda"

[optimizer]
learning_rate = 0.001
beta1 = 0.9
beta2 = 0.995
eps = 1e-8
weight_decay = 0.01
max_grad_norm = 1.0

[training]
batch_size = 128
max_iters = 1000
log_training_loss_every = 10
log_validation_loss_every = 100

[lr_schedule]
warmup_iters = 100
cosine_cycle_iters = 10000
min_learning_rate = 0.0001

[checkpoint]
output_file = "/cs336/assignment1/data/model/post_norm_lr1e-3_1k"

[logging]
dir = "/cs336/assignment1/logging/post_norm_lr1e-3_1k"
