tokenizer_filepath = "data/tokenizer.pkl"
model_filepath = "data/model/checkpoint"
prompt = "Tom was a young lad."
[model]
vocab_size = 1001
context_length = 128
d_model = 128
num_layers = 2
num_heads = 4
d_ff = 384
rope_theta = 10000.0