#corpus_filepath = "data/samples/owt-10-docs.txt"
#merges_pickle = "data/owt/merges.pkl"
#vocab_pickle = "data/owt/vocab.pkl"

corpus_filepath = "data/TinyStoriesV2-GPT4-valid.txt"
merges_pickle = "data/tiny-stories/merges.pkl"
vocab_pickle = "data/tiny-stories/vocab.pkl"